# Project: LiquidGalaxy
# Makefile created by Dev-C++ 6.7.5

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = LiquidGalaxy_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/" -L"C:/msys64/ucrt64/lib/gcc/" -L"C:/msys64/ucrt64/x86_64-w64-mingw32/lib/" -L"C:/msys64/ucrt64/lib/" -L"C:/msys64/ucrt64/lib" -L"C:/msys64/ucrt64/x86_64-w64-mingw32/lib" -s -static-libgcc -static-libstdc++ -Wl,--gc-sections -Wl,--strip-all -s -luser32 -lkernel32 -lgdi32 -lshell32 -static
INCS     = -I"C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/include" -I"C:/msys64/ucrt64/include" -I"C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/include-fixed"
CXXINCS  = -I"C:/msys64/ucrt64/include/c++/15.2.0" -I"C:/msys64/ucrt64/include/c++/15.2.0/x86_64-w64-mingw32" -I"C:/msys64/ucrt64/include/c++/15.2.0/backward" -I"C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/include" -I"C:/msys64/ucrt64/include" -I"C:/msys64/ucrt64/lib/gcc/x86_64-w64-mingw32/15.2.0/include-fixed"
BIN      = LiquidGalaxy.exe
CXXFLAGS = $(CXXINCS) -O2 -Os -fdata-sections
ENCODINGS = -finput-charset=utf-8 -fexec-charset=gbk
CFLAGS   = $(INCS) -O2
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "$(BIN)" $(LIBS)

main.o: main.cpp achieve.h config.h getuuid.h INCLUDE.h mod.h
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)  $(ENCODINGS) 

LiquidGalaxy_private.res: LiquidGalaxy_private.rc 
	$(WINDRES) -i LiquidGalaxy_private.rc --input-format=rc -o LiquidGalaxy_private.res -O coff 

